import type { Metadata } from "next";
import { IBM_Plex_Mono, Manrope, Newsreader } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

import "@/app/globals.css";

const themeScript = `
  (() => {
    try {
      const root = document.documentElement;
      const storedTheme = window.localStorage.getItem("sideout-theme");
      const systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
      const resolvedTheme =
        storedTheme === "light" || storedTheme === "dark"
          ? storedTheme
          : systemDark
            ? "dark"
            : "light";

      root.dataset.theme = resolvedTheme;
      root.style.colorScheme = resolvedTheme;
    } catch (error) {
      document.documentElement.dataset.theme = "light";
      document.documentElement.style.colorScheme = "light";
    }
  })();
`;

const sans = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
});

const display = Newsreader({
  subsets: ["latin"],
  variable: "--font-display",
  style: ["normal", "italic"],
});

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
});

const siteDescription =
  "Booking, memberships, and a front-desk console for a family-run pickleball club in Dehradun.";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"),
  title: {
    default: "Sideout — Dehradun Pickleball Club",
    template: "%s | Sideout",
  },
  description: siteDescription,
  openGraph: {
    type: "website",
    siteName: "Sideout",
    title: "Sideout — Dehradun Pickleball Club",
    description: siteDescription,
    // The image is generated by app/opengraph-image.tsx (Next 16 ImageResponse).
  },
  twitter: {
    card: "summary_large_image",
    title: "Sideout — Dehradun Pickleball Club",
    description: siteDescription,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className={`${sans.variable} ${display.variable} ${mono.variable} antialiased`}>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
